[package]
name = "aoc"
version = "0.1.0"
authors = ["James Addison <jay@jp-hosting.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
